/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "s3ePixelDensity_autodefs.h"
#include "s3eEdk.h"
#include "s3ePixelDensity.h"
//Declarations of Init and Term functions
extern s3eResult s3ePixelDensityInit();
extern void s3ePixelDensityTerminate();


// On platforms that use a seperate UI/OS thread we can autowrap functions
// here.   Note that we can't use the S3E_USE_OS_THREAD define since this
// code is oftern build standalone, outside the main loader build.
#if defined I3D_OS_IPHONE || defined I3D_OS_OSX || defined I3D_OS_LINUX || defined I3D_OS_WINDOWS

static int s3ePixelDensityGetPPI_wrap()
{
    IwTrace(PIXELDENSITY_VERBOSE, ("calling s3ePixelDensity func on main thread: s3ePixelDensityGetPPI"));
    return (int)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3ePixelDensityGetPPI, 0);
}

#define s3ePixelDensityGetPPI s3ePixelDensityGetPPI_wrap

#endif

void s3ePixelDensityRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[1];
    funcPtrs[0] = (void*)s3ePixelDensityGetPPI;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[1] = { 0 };

    /*
     * Register the extension
     */
s3eEdkRegister("s3ePixelDensity", funcPtrs, sizeof(funcPtrs), flags, s3ePixelDensityInit, s3ePixelDensityTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int s3ePixelDensityStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&s3ePixelDensityRegisterExt;
    return 0;
}

int g_s3ePixelDensityVal = s3ePixelDensityStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    s3ePixelDensityRegisterExt();
}
#endif

#endif
