/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EPIXELDENSITY_AUTODEFS_H
#define S3EPIXELDENSITY_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_PIXELDENSITY_NAME "s3ePixelDensity"
#define S3E_EXT_PIXELDENSITY_HASH 0xb93780f2

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("s3ePixelDensity", 1)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !S3EPIXELDENSITY_AUTODEFS_H */
