/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef        int(*s3ePixelDensityGetPPI_t)();

/**
 * struct that gets filled in by s3ePixelDensityRegister
 */
typedef struct s3ePixelDensityFuncs
{
    s3ePixelDensityGetPPI_t m_s3ePixelDensityGetPPI;
} s3ePixelDensityFuncs;
